# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activeadmin}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Bell"]
  s.date = %q{2010-09-07}
  s.description = %q{The administration framework for Ruby on Rails.}
  s.email = %q{gregdbell@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "active_admin.gemspec",
     "lib/active_admin.rb",
     "lib/active_admin/action_builder.rb",
     "lib/active_admin/action_items.rb",
     "lib/active_admin/asset_registration.rb",
     "lib/active_admin/breadcrumbs.rb",
     "lib/active_admin/dashboards.rb",
     "lib/active_admin/dashboards/dashboard_controller.rb",
     "lib/active_admin/dashboards/renderer.rb",
     "lib/active_admin/dashboards/section.rb",
     "lib/active_admin/dashboards/section_renderer.rb",
     "lib/active_admin/filters.rb",
     "lib/active_admin/form_builder.rb",
     "lib/active_admin/helpers/optional_display.rb",
     "lib/active_admin/menu.rb",
     "lib/active_admin/menu_item.rb",
     "lib/active_admin/namespace.rb",
     "lib/active_admin/page_config.rb",
     "lib/active_admin/pages.rb",
     "lib/active_admin/pages/base.rb",
     "lib/active_admin/pages/edit.rb",
     "lib/active_admin/pages/index.rb",
     "lib/active_admin/pages/index/blog.rb",
     "lib/active_admin/pages/index/table.rb",
     "lib/active_admin/pages/index/thumbnails.rb",
     "lib/active_admin/pages/new.rb",
     "lib/active_admin/pages/show.rb",
     "lib/active_admin/renderer.rb",
     "lib/active_admin/resource.rb",
     "lib/active_admin/resource_controller.rb",
     "lib/active_admin/sidebar.rb",
     "lib/active_admin/table_builder.rb",
     "lib/active_admin/tabs_renderer.rb",
     "lib/active_admin/version.rb",
     "lib/active_admin/view_helpers.rb",
     "lib/active_admin/views/active_admin_dashboard/index.html.erb",
     "lib/active_admin/views/active_admin_default/edit.html.erb",
     "lib/active_admin/views/active_admin_default/index.csv.erb",
     "lib/active_admin/views/active_admin_default/index.html.erb",
     "lib/active_admin/views/active_admin_default/new.html.erb",
     "lib/active_admin/views/active_admin_default/show.html.erb",
     "lib/active_admin/views/layouts/active_admin.html.erb",
     "lib/activeadmin.rb",
     "lib/generators/active_admin/install/install_generator.rb",
     "lib/generators/active_admin/install/templates/active_admin.css",
     "lib/generators/active_admin/install/templates/active_admin.js",
     "lib/generators/active_admin/install/templates/active_admin.rb",
     "lib/generators/active_admin/install/templates/active_admin_vendor.js",
     "lib/generators/active_admin/install/templates/dashboards.rb",
     "lib/generators/active_admin/install/templates/images/orderable.gif",
     "lib/generators/active_admin/resource/resource_generator.rb",
     "lib/generators/active_admin/resource/templates/admin.rb",
     "spec/integration/dashboard_spec.rb",
     "spec/integration/index_as_blog_spec.rb",
     "spec/integration/index_as_csv_spec.rb",
     "spec/integration/index_as_table_spec.rb",
     "spec/integration/index_as_thumbnails_spec.rb",
     "spec/integration/layout_spec.rb",
     "spec/integration/new_view_spec.rb",
     "spec/integration/show_view_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/rails_template.rb",
     "spec/unit/action_builder_spec.rb",
     "spec/unit/action_items_spec.rb",
     "spec/unit/active_admin_spec.rb",
     "spec/unit/asset_registration_spec.rb",
     "spec/unit/controller_filters_spec.rb",
     "spec/unit/dashboard_section_spec.rb",
     "spec/unit/dashboards_spec.rb",
     "spec/unit/filter_form_builder_spec.rb",
     "spec/unit/form_builder_spec.rb",
     "spec/unit/menu_item_spec.rb",
     "spec/unit/menu_spec.rb",
     "spec/unit/namespace_spec.rb",
     "spec/unit/registration_spec.rb",
     "spec/unit/renderer_spec.rb",
     "spec/unit/resource_controller_spec.rb",
     "spec/unit/resource_spec.rb",
     "spec/unit/routing_spec.rb",
     "spec/unit/sidebar_spec.rb",
     "spec/unit/table_builder_spec.rb",
     "spec/unit/tabs_renderer_spec.rb"
  ]
  s.homepage = %q{http://github.com/gregbell/active_admin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{The administration framework for Ruby on Rails.}
  s.test_files = [
    "spec/integration/dashboard_spec.rb",
     "spec/integration/index_as_blog_spec.rb",
     "spec/integration/index_as_csv_spec.rb",
     "spec/integration/index_as_table_spec.rb",
     "spec/integration/index_as_thumbnails_spec.rb",
     "spec/integration/layout_spec.rb",
     "spec/integration/new_view_spec.rb",
     "spec/integration/show_view_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/rails_template.rb",
     "spec/unit/action_builder_spec.rb",
     "spec/unit/action_items_spec.rb",
     "spec/unit/active_admin_spec.rb",
     "spec/unit/asset_registration_spec.rb",
     "spec/unit/controller_filters_spec.rb",
     "spec/unit/dashboard_section_spec.rb",
     "spec/unit/dashboards_spec.rb",
     "spec/unit/filter_form_builder_spec.rb",
     "spec/unit/form_builder_spec.rb",
     "spec/unit/menu_item_spec.rb",
     "spec/unit/menu_spec.rb",
     "spec/unit/namespace_spec.rb",
     "spec/unit/registration_spec.rb",
     "spec/unit/renderer_spec.rb",
     "spec/unit/resource_controller_spec.rb",
     "spec/unit/resource_spec.rb",
     "spec/unit/routing_spec.rb",
     "spec/unit/sidebar_spec.rb",
     "spec/unit/table_builder_spec.rb",
     "spec/unit/tabs_renderer_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0"])
      s.add_runtime_dependency(%q<formtastic>, [">= 1.1.0.beta"])
      s.add_runtime_dependency(%q<will_paginate>, [">= 3.0.pre2"])
      s.add_runtime_dependency(%q<meta_search>, [">= 0.9.2"])
      s.add_runtime_dependency(%q<inherited_views>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0"])
      s.add_dependency(%q<formtastic>, [">= 1.1.0.beta"])
      s.add_dependency(%q<will_paginate>, [">= 3.0.pre2"])
      s.add_dependency(%q<meta_search>, [">= 0.9.2"])
      s.add_dependency(%q<inherited_views>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0"])
    s.add_dependency(%q<formtastic>, [">= 1.1.0.beta"])
    s.add_dependency(%q<will_paginate>, [">= 3.0.pre2"])
    s.add_dependency(%q<meta_search>, [">= 0.9.2"])
    s.add_dependency(%q<inherited_views>, [">= 0"])
  end
end

