codecov:
  notify:
    require_ci_to_pass: true
comment: off
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
parsers:
  javascript:
    enable_partials: false
