source "https://rubygems.org"

group :development, :test do
  gem "rake"
  gem "pry" # Easily debug from your console with `binding.pry`
  gem "pry-byebug", platform: :mri # Step-by-step debugging

  gem "cancancan"
  gem "pundit"
  gem "jruby-openssl", "~> 0.10.5", platform: :jruby

  gem "draper", "~> 4.0"
  gem "devise"

  gem "rails", "~> 6.1.0"
  gem "activerecord-jdbcsqlite3-adapter", "~> 61.0", platform: :jruby

  gem "webpacker", "~> 5.1"

  gem "formtastic", "~> 4.0.rc1"
end

group :test do
  gem "cuprite", "0.13"
  gem "capybara", "~> 3.14"
  gem "webrick", "~> 1.7"
  gem "db-query-matchers", "0.10.0"

  gem "simplecov", "0.21.2", require: false # Test coverage generator. Go to /coverage/ after running tests
  gem "cucumber-rails", "~> 2.0", require: false
  gem "cucumber"
  gem "database_cleaner"
  gem "jasmine"
  gem "jasmine-core", "2.99.2" # last release with Ruby 2.2 support.
  gem "launchy"
  gem "parallel_tests", "~> 3.0"
  gem "rails-i18n" # Provides default i18n for many languages
  gem "rspec-rails"
  gem "sqlite3", "~> 1.4", platform: :mri
  gem "ammeter"
end

gemspec path: "../.."
