blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/activeadmin/activeadmin/discussions/new?category=help
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
  - name: Feature Request
    url: https://github.com/activeadmin/activeadmin/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
  - name: Documentation Issue
    url: https://github.com/activeadmin/activeadmin/pulls
    about: For documentation improvements, feel free to create a pull request.
  - name: Localization Issue
    url: https://github.com/activeadmin/activeadmin/pulls
    about: For any localization updates, create a pull request as we rely entirely on the community for these.
