#!/usr/bin/env ruby

require 'shellwords'

unless ARGV[0]
  puts <<-EOF
Usage: #{__FILE__} COMMAND [ARGS]

The command will be run in the context of the local rails
app stored in test-rails-app.

Examples:

#{__FILE__} server
#{__FILE__} c
#{__FILE__} rake db:migrate
  EOF
  exit(1)
end

require 'rails'

# Set up some variables
dir = ".test-rails-apps"
path = "#{dir}/test-rails-app-#{Rails.version}"

# Ensure .test-rails-apps is created
system "mkdir #{dir}" unless File.exist?(dir)

# Create the sample rails app if it doesn't already exist
unless File.exist? path
  args = %w[
    -m spec/support/rails_template_with_data.rb
    --skip-bundle
    --skip-listen
    --skip-turbolinks
    --skip-test-unit
  ]
  system "rails new #{Shellwords.escape path} #{args.join ' '}"
end

# Link this rails app
system "rm test-rails-app"
system "ln -s #{Shellwords.escape path} test-rails-app"

# If it's a rails command, auto add the rails script
RAILS_COMMANDS = %w{generate console server dbconsole g c s runner}
args = RAILS_COMMANDS.include?(ARGV[0]) ? ["rails", ARGV].flatten : ARGV

# Run the command
exec "cd test-rails-app && #{args.join(" ")}"
