#!/usr/bin/env ruby
#
# Switches the development environment to use the given
# version of rails. Caches the Gemfile.locks so that 
# switching it very fast.

def cmd(command)
  puts command
  system command
end

version = ARGV[0]

unless version
  puts "usage: ./script/#{__FILE__} VERSION"
  exit(1)
end

def file_or_symlink?(path)
  File.exist?(path) || File.symlink?(path)
end

gem_lock_dir = ".gemfile-locks"
gem_lock_file = "#{gem_lock_dir}/Gemfile-#{version}.lock"

# Ensure our lock dir is created
cmd "mkdir #{gem_lock_dir}" unless File.exists?(gem_lock_dir)

unless File.exists?(gem_lock_file)
  cmd "rm Gemfile.lock" if file_or_symlink?("Gemfile.lock")
  cmd "export RAILS=#{version} && bundle install"
  cmd "mv Gemfile.lock #{gem_lock_file}"
end

cmd("rm Gemfile.lock") if file_or_symlink?("Gemfile.lock")
cmd("ln -s #{gem_lock_file} Gemfile.lock")
