source 'http://rubygems.org'

gem 'rails', '3.0.0.beta3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'formtastic', :git => "http://github.com/justinfrench/formtastic.git", :branch => 'rails3'
gem 'inherited_views'

gem 'will_paginate', :git => 'http://github.com/mislav/will_paginate.git', :branch => 'rails3'
gem "meta_search", :git => "git://github.com/ernie/meta_search.git"

group :test do
  gem 'rspec', '>=2.0.0.beta.6'
  gem 'rspec-rails', '>=2.0.0.beta.6'
end
