# frozen_string_literal: true
source "https://rubygems.org"

group :development, :test do
  gem "rake"

  gem "cancancan"
  gem "pundit"

  gem "draper"

  # Devise 5 requires Formtastic 6, which requires Ruby 3.2. This Rails version
  # is tested against Ruby 3.1, so this dependency cannot be relaxed
  gem "devise", "~> 4.9"

  gem "rails", "~> 7.1.0"

  gem "sprockets-rails"
  gem "sassc-rails"
  gem "ransack", ">= 4.1.0"

  # FIXME: relax this dependency when Ruby 3.1 support will be dropped
  gem "zeitwerk", "~> 2.6.18"
end

group :test do
  gem "cuprite"
  gem "capybara"
  gem "webrick"

  gem "simplecov", require: false # Test coverage generator. Go to /coverage/ after running tests
  gem "simplecov-cobertura", require: false
  gem "cucumber-rails", require: false
  gem "cucumber"
  gem "database_cleaner-active_record"
  gem "launchy"
  gem "parallel_tests"
  gem "rspec-rails"
  gem "sqlite3", platform: :mri

  # Translations
  gem "i18n-tasks"
  gem "i18n-spec"
  gem "rails-i18n" # Provides default i18n for many languages
end

group :release do
  gem "chandler" # Github releases from changelog
  gem "octokit"
end

group :rubocop do
  gem "rubocop"
  gem "rubocop-packaging"
  gem "rubocop-rspec"
  gem "rubocop-rails"
end

group :docs do
  gem "yard" # Documentation generator
  gem "kramdown" # Markdown implementation (for yard)
end

gemspec path: "../.."
