name: Bug Reports

on:
  pull_request:
    # If updating `paths-ignore` then update bug-report-template.yml to match
    paths-ignore:
      - '.github/workflows/bug-report-template.yml'
      - 'tasks/bug_report_template.rb'

jobs:
  bug_report_template_test:
    name: Run bug report template
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Do nothing"
