name: JS Lint

on:
  pull_request:
    # If updating `paths-ignore` then update eslint.yml to match
    paths-ignore:
      - '.eslintignore'
      - '.eslintrc.yml'
      - '.github/workflows/eslint.yml'
      - 'package*.json'
      - 'yarn.lock'
      - '**.js'

jobs:
  eslint:
    name: Run eslint
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Do nothing"
