name: Gherkin Lint

on:
  pull_request:
    # If updating `paths-ignore` then update gherkin-lint.yml to match
    paths-ignore:
      - '.github/workflows/gherkin-lint.yml'
      - '.gherkin-lintignore'
      - '.gherkin-lintrc'
      - 'package*.json'
      - '**.feature'

jobs:
  gherkin_lint:
    name: Run gherkin-lint
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Do nothing"
